using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class WeaponSpawnPoint : MonoBehaviour {
    [Tooltip("Use the prefab address for the weapon you want to spawn here. Works with modded content. Addresses can be found in the 'data' lua scripts of other mods.")]
    public string PriorityWeaponPrefabAddress;

    [Tooltip("If Priority weapon ID is left blank or cannot find a matching weapon, the game will spawn this built-in weapon here.")]
    public BuiltInWeaponID FallbackWeapon = BuiltInWeaponID.Hammer;

    public enum BuiltInWeaponID {
       AssaultRifleAK47,
       AssaultRifleG36C,
       AssaultRifleM4,
       AssaultRifleM16,
       AssaultRifleScar,
       WoodenBow,
       EnergyRifle,
       GravityGun,
       MakeshiftRifle,
       MakeshiftSawn,
       MakeshiftSniper,
       PistolDeagle,
       PistolGlock,
       PistolM1911,
       PistolStar,
       ShotgunPump,
       SubMP5,
       SubMP5k,
       SubMP7,
       HunterKnife,
       HunterKnife2,
       ApolloKatana,
       Axe,
       AxeFire,
       AxeNorse,
       AxePick,
       AxePrimative,
       AxeSawBlade,
       AxeWar,
       AxeWar2,
       BaseballBat,
       BattleHammer,
       BattleHammer2,
       BattleHammer3,
       BattleHammer4,
       BattleHammerSmall,
       BattleHammerSmall21,
       BattleHammerSmall2,
       BattleMace,
       BoxingGloveLeft,
       BoxingGloveRight,
       Brick,
       Broom,
       Cane,
       ClubPrimative,
       Crowbar,
       Dumbbell,
       GardenFork,
       Golfclub,
       GuitarAcoustic,
       GuitarElectricBass,
       GuitarElectricMetal,
       GuitarElectricRock,
       Hammer,
       HunterKnives,
       IceAxe,
       KettleBell,
       KnifeBone,
       KnifeClimbing,
       KnifeCombat,
       KnifeDemon,
       KnifeKitchen,
       KnifeMedieval,
       KnifeMedieval2,
       KnifePocket,
       KnifePrimative,
       KnifeSacrificial,
       KnifeSharp,
       KnifeThief,
       KnucklesBlade,
       KnucklesMetal,
       KnucklesWolverine,
       LaptopBag,
       Pan,
       Pickaxe,
       PoolCue,
       Screwdriver,
       Shovel,
       Sledgehammer,
       Spanner,
       Spear,
       Spear2,
       Spear3,
       SwordButchersBlade,
       SwordCutlass,
       SwordGreatsword,
       SwordMedieval,
       SwordMedieval2,
       SwordNeon,
       SwordOdachi,
       SwordSavage,
       Wrench

    }

    [Tooltip("Weapon mods allow for weapons to be automatically replaced. Disable this option to force this weapon to be the one configured here.")]
    public bool AllowReplacements;
}
